title:  "Clarkinia Astrology"
tagline:

url: "https://www.clarkiniaastrology.com/"

social-connect:
- {icon: 'facebook', link: 'https://vimeo.com/12326391'}
- {icon: 'instagram', link: 'https://www.youtube.com/watch?v=C-ypQm2FimA'}
- {icon: 'mastodon', link: 'https://mastodon.social/@Clarkinia/'}
