title:  "Clarkinia Astrology"
tagline:

url: "https://www.clarkiniaastrology.com/"

social-connect:
- {icon: 'facebook', link: 'https://facebook.com/clarkinia'}
- {icon: 'instagram', link: 'https://instagram.com/clarkinia/'}
- {icon: 'mastodon', link: 'https://mastodon.social/@Clarkinia/'}

image: noun_103916_cc_horiz.gif
header: Clarkinia Astrology
